# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.ResponseType" do
  end
  add_message "protocol.RequestType" do
  end
  add_message "protocol.Person" do
    optional :name, :string, 1
    optional :age, :int32, 2
  end
end

module Protocol
  ResponseType = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.ResponseType").msgclass
  RequestType = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.RequestType").msgclass
  Person = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.Person").msgclass
end
