# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    environment:
#          GOPATH: {{HOME}}/.go
      ORG_NAME: origin
      REPO_NAME: master
#    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    working_directory: /go/src/github.com/origin/master
    steps:
      - checkout
      - run: go get ./...
      - run: go test -v ./...
