# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    environment:
    working_directory: /go/src/github.com/sak0620/chaos
    steps:
      - checkout
      - run: go get ./...
      - run: go test -v ./...
